version: '3.2'

services:
  elastic:
    build:
      context: ./docker_elasticsearch
      dockerfile: Dockerfile
    container_name: search-inside-elastic
    environment:
      - "ES_JAVA_OPTS=-Xms4096m -Xmx4096m"
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      # - logger.level=WARN
    ports:
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana:8.2.0
    container_name: search-inside-kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://search-inside-elastic:9200
      - ELASTICSEARCH_HOSTS=http://search-inside-elastic:9200
    depends_on:
      - elastic
  nodejsb:
    build:
      context: ./docker_nodejsb
      dockerfile: Dockerfile-dev
    container_name: search-inside-nodejsb
    ports:
      - "5602:5602"
    environment:
      - RUNNING_HOST=local
    depends_on:
      - elastic
    command: ./wait-for.sh --timeout=0 elastic:9200 -- nodemon push_to_elasticsearch.js
    volumes:
      - ./docker_nodejsb/wait-for.sh:/app/wait-for.sh
      - ./docker_nodejsb/push_to_elasticsearch.js:/app/push_to_elasticsearch.js
  nodejsf:
    build:
      context: ./docker_nodejsf
      dockerfile: Dockerfile-dev
    container_name: search-inside-nodejsf
    ports:
      - "5603:5603"
    depends_on:
      - elastic
    command: nodemon /app/serverf.js
    volumes:
      - ./docker_nodejsf/serverf.js:/app/serverf.js
