version: '3.2'

services:
  elastic:
    build:
      context: ./docker_elasticsearch
      dockerfile: Dockerfile
      args:
        - SEARCH_INSIDE_API_RO_USERNAME=${SEARCH_INSIDE_API_RO_USERNAME}
        - SEARCH_INSIDE_API_RO_PASSWORD=${SEARCH_INSIDE_API_RO_PASSWORD}
        - SEARCH_INSIDE_KIBANA_PASSWORD=${SEARCH_INSIDE_KIBANA_PASSWORD}
        - INSIDE_HOST=inside.epfl.ch
        - BUILD_ENV=local
    container_name: search-inside-elastic
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=${SEARCH_INSIDE_ELASTIC_PASSWORD}
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    # volumes:
    #   - ./.elastic_data:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:8.3.1
    container_name: search-inside-kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://search-inside-elastic:9200
      - ELASTICSEARCH_HOSTS=http://search-inside-elastic:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${SEARCH_INSIDE_KIBANA_PASSWORD}
    depends_on:
      - elastic
  nodeapi:
    build:
      context: ./docker_nodeapi
      dockerfile: Dockerfile-dev
    container_name: search-inside-nodeapi
    environment:
      - SEARCH_INSIDE_SEARCH_URL=http://localhost:3000
      - SEARCH_INSIDE_ELASTICSEARCH_URL=http://search-inside-elastic:9200
      - SEARCH_INSIDE_SESSION_SECRET=${SEARCH_INSIDE_SESSION_SECRET}
      - SEARCH_INSIDE_ALLOW_EXTERNAL=True
      - SEARCH_INSIDE_API_RO_USERNAME=${SEARCH_INSIDE_API_RO_USERNAME}
      - SEARCH_INSIDE_API_RO_PASSWORD=${SEARCH_INSIDE_API_RO_PASSWORD}
      - NODE_ENV=development
    command: npm run start
    ports:
      - "4444:4444"
    depends_on:
      - elastic
    volumes:
      - ./docker_nodeapi/serverapi.js:/app/serverapi.js
