services:
  api:
    build:
      context: ./docker_api
    container_name: search-inside-api
    environment:
      - SEARCH_INSIDE_SEARCH_URL=http://localhost:3000
      - SEARCH_INSIDE_ELASTICSEARCH_URL=http://search-inside-elastic:9200
      - SEARCH_INSIDE_SESSION_SECRET=${SEARCH_INSIDE_SESSION_SECRET}
      - SEARCH_INSIDE_ALLOW_EXTERNAL=True
      - SEARCH_INSIDE_API_RO_USERNAME=${SEARCH_INSIDE_API_RO_USERNAME}
      - SEARCH_INSIDE_API_RO_PASSWORD=${SEARCH_INSIDE_API_RO_PASSWORD}
      - NODE_ENV=development
    command: npm run start
    ports:
      - "4444:4444"
    depends_on:
      - elastic
    volumes:
      - ./docker_api/serverapi.js:/app/serverapi.js
