version: '3.2'

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: search-inside-kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://search-inside-elastic:9200
      - ELASTICSEARCH_HOSTS=http://search-inside-elastic:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${SEARCH_INSIDE_KIBANA_PASSWORD}
    depends_on:
      - elastic
