- name: API - Include Secrets
  include_tasks:
    file: 'secrets.yml'

- name: API - Builder Pull Secret
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      type: kubernetes.io/dockerconfigjson
      metadata:
        name: search-inside-api-builder-pull-secret
        namespace: "{{ openshift_namespace }}"
      data:
        .dockerconfigjson: "{{ pull_secret_api_builder_config | to_json | b64encode }}"

- name: API - Builder Service Account
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: search-inside-api-builder
        namespace: "{{ openshift_namespace }}"
      secrets:
        - name: search-inside-api-builder-pull-secret
      # This is not supposed to be required (it worked without in
      # OpenShift 4.14); but see
      # https://access.redhat.com/solutions/7098226
      imagePullSecrets:
        - name: search-inside-api-builder-pull-secret

- name: API - Build Config
  kubernetes.core.k8s:
    definition:
      apiVersion: build.openshift.io/v1
      kind: BuildConfig
      metadata:
        name: search-inside-api
        namespace: "{{ openshift_namespace }}"
      spec:
        serviceAccount: search-inside-api-builder
        source:
          type: Git
          git:
            uri: "{{ search_inside_api_git_uri }}"
            ref: "{{ search_inside_api_git_branch }}"
          contextDir: docker_api
        strategy:
          type: Docker
          dockerStrategy:
            forcePull: true
        triggers:
          - type: ConfigChange
        output:
          to:
            kind: DockerImage
            name: "{{ search_inside_api_image }}"
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"

- name: API - Start build
  when: >-
    "api.startbuild" in ansible_run_tags
  shell:
    cmd: "oc -n {{ openshift_namespace }} start-build --wait search-inside-api"
  tags:
    - api.startbuild
