- name: API - Secrets
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: search-inside-api-secrets
        namespace: "{{ openshift_namespace }}"
      type: Opaque
      data: >-
        {{ _data | from_yaml }}
  vars:
    _data: |
      SEARCH_INSIDE_SESSION_SECRET: "{{ search_inside_session_secret | b64encode }}"
      SEARCH_INSIDE_API_RO_USERNAME: "{{ search_inside_api_ro_username | b64encode }}"
      SEARCH_INSIDE_API_RO_PASSWORD: "{{ search_inside_api_ro_password | b64encode }}"
