- name: API - Image
  when:
    - inventory_environment == "test"
  include_tasks:
    file: 'api/image.yml'
    apply:
      tags:
        - api
        - api.image
  tags:
    - api
    - api.image
    - api.startbuild

- name: API - App
  include_tasks:
    file: 'api/app.yml'
    apply:
      tags:
        - api
        - api.app
  tags:
    - api
    - api.app
    - api.restart

- name: Elastic - Image
  when:
    - inventory_environment == "test"
  include_tasks:
    file: 'elastic/image.yml'
    apply:
      tags:
        - elastic
  tags:
    - elastic
    - elastic.startbuild

- name: Elastic - App
  include_tasks:
    file: 'elastic/app.yml'
    apply:
      tags:
        - elastic
  tags:
    - elastic
    - elastic.restart
