- name: API - Image
  when:
    - inventory_environment == "test"
  include_tasks:
    file: 'api/image.yml'
    apply:
      tags:
        - api
        - api.image
  tags:
    - api
    - api.image
    - api.image.startbuild

- name: API - App
  include_tasks:
    file: 'api/app.yml'
    apply:
      tags:
        - api
        - api.app
  tags:
    - api
    - api.app
    - api.app.restart

- name: Elastic - Image
  include_tasks:
    file: 'elastic/image.yml'
    apply:
      tags:
        - elastic
        - elastic.image
  tags:
    - elastic
    - elastic.image
    - elastic.image.startbuild

- name: Elastic - App
  include_tasks:
    file: 'elastic/app.yml'
    apply:
      tags:
        - elastic
        - elastic.app
  tags:
    - elastic
    - elastic.app
    - elastic.app.restart

- name: Elastic - Tekton RBAC
  when:
    - inventory_environment == "test"
  include_tasks:
    file: 'elastic/tekton-rbac.yml'
    apply:
      tags:
        - elastic
        - elastic.tekton-rbac
  tags:
    - elastic
    - elastic.tekton-rbac

- name: Elastic - Tekton
  when:
    - inventory_environment == "test"
  include_tasks:
    file: 'elastic/tekton.yml'
    apply:
      tags:
        - elastic
        - elastic.tekton
  tags:
    - elastic
    - elastic.tekton
    - elastic.tekton.run-pipeline

- name: Elastic - Prod Daily Rollout
  when:
    - inventory_environment == "prod"
  include_tasks:
    file: 'elastic/prod-daily-rollout.yml'
    apply:
      tags:
        - elastic
        - elastic.prod-daily-rollout
  tags:
    - elastic
    - elastic.prod-daily-rollout

- name: Monitoring
  include_tasks:
    file: 'monitoring.yml'
    apply:
      tags:
        - monitoring
  tags:
    - monitoring
