- name: Elastic - Secrets
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: search-inside-elastic-secrets
        namespace: "{{ openshift_namespace }}"
      type: Opaque
      data: >-
        {{ _data | from_yaml }}
  vars:
    _data: |
      SEARCH_INSIDE_ELASTIC_PASSWORD: "{{ search_inside_elastic_password | b64encode }}"
      SEARCH_INSIDE_KIBANA_PASSWORD: "{{ search_inside_kibana_password | b64encode }}"
      SEARCH_INSIDE_API_RO_USERNAME: "{{ search_inside_api_ro_username | b64encode }}"
      SEARCH_INSIDE_API_RO_PASSWORD: "{{ search_inside_api_ro_password | b64encode }}"
